#!/bin/bash
#PBS -l walltime=5:00:00
#PBS -l select=1:ncpus=1:mem=80gb:ngpus=1:gpu_type=A100
#PBS -q hx
#PBS -N ligandmpnn

export HYDRA_FULL_ERROR=1

cd $PBS_O_WORKDIR
cat $PBS_NODEFILE

source activate ligandmpnn

module load CUDA/12.1.0

cd modules/LigandMPNN

# python run.py \
#         --model_type "soluble_mpnn" \
#         --seed 111 \
#         --pdb_path "../../data/designs/dimer1/fixed.pdb" \
#         --out_folder "../../outputs/dimer1/SolubleMPNN" \
#         --chains_to_design "C" \
#         --batch_size 10 \
#         --number_of_batches 100

# # print that you finished with dimer1
# echo "Finished with dimer1"

# python run.py \
#         --model_type "soluble_mpnn" \
#         --seed 111 \
#         --pdb_path "../../data/designs/dimer5/fixed.pdb" \
#         --out_folder "../../outputs/dimer5/SolubleMPNN" \
#         --chains_to_design "C" \
#         --batch_size 10 \
#         --number_of_batches 100

# # print that you finished with dimer5
# echo "Finished with dimer5"

for type in simpleAA simpleBB simpleAB
do
    for i in {0..9}
    do
        python run.py \
            --model_type "soluble_mpnn" \
            --seed 111 \
            --pdb_path "../../outputs/simple/${type}/RFDiffusion/_${i}.pdb" \
            --out_folder "../../outputs/${type}/SolubleMPNN" \
            --chains_to_design "A" \
            --fixed_residues "C1 C2 C3 C4 C5 C6 C7 C8 C9 C10 C11 C12 C13 C14 C15 C16 C17 C18 C19 C20 C61 C62 C63 C64 C65 C66 C67 C68 C69 C70 C71 C72 C73 C74 C75 C76 C77 C78 C79 C80" \
            --batch_size 10 \
            --number_of_batches 5
    done
done
