#!/bin/bash
#PBS -l walltime=5:00:00
#PBS -l select=1:ncpus=1:mem=80gb:ngpus=1:gpu_type=A100
#PBS -q hx
#PBS -N esmfold

export TRANSFORMERS_DIR="/gpfs/home/jl24018/projects/transformers"

cd $PBS_O_WORKDIR
cat $PBS_NODEFILE

module load CUDA/12.1.0
module load GCC/13.2.0
source activate new-protein

python scripts/run_esmfold.py

