#!/bin/bash
#PBS -l walltime=5:00:00
#PBS -l select=1:ncpus=1:mem=80gb:ngpus=1:gpu_type=A100
#PBS -q hx
#PBS -N rfdiffusion

export HYDRA_FULL_ERROR=1

cd $PBS_O_WORKDIR
cat $PBS_NODEFILE

source activate bits-in-binder

module load CUDA/11.8.0

# ppi.hotspot_res=[P173,A83,A91] \

# for epitope
# python modules/RFdiffusion/scripts/run_inference.py \
#     inference.input_pdb=data/3pp4.pdb \
#     inference.output_prefix=outputs/3pp4/ \
#     'contigmap.contigs=[A1-24/0 80-80]' \
#     inference.num_designs=100 \
#     denoiser.noise_scale_ca=0 \
#     denoiser.noise_scale_frame=0


python modules/RFdiffusion/scripts/run_inference.py \
    inference.input_pdb=data/3pp4.pdb \
    inference.output_prefix=outputs/3pp4/ \
    'contigmap.contigs=[A1-24/0 80-80]' \
    inference.num_designs=100 \
    denoiser.noise_scale_ca=0 \
    denoiser.noise_scale_frame=0

